import = [
    "~/.config/alacritty/themes/themes/hackthebox.toml"
]
#
[cursor]
thickness = 0.05

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
# size = 20.0
size = 16.0

[font.bold]
# family = "CaskaydiaCove Nerd Font Propo"
#family = "JetBrainsMono Nerd Font Mono"
family = "ProFont IIx Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "JetBrainsMono Nerd Font Mono"
family = "ProFont IIx Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "JetBrainsMono Nerd Font Mono"
family = "ProFont IIx Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "JetBrainsMono Nerd Font Mono"
family = "ProFont IIx Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "Transparent"
# decorations = "buttonless"
opacity = 0.90
blur = true
dynamic_padding = true

[window.padding]
x = 25
y = 25

[keyboard]
bindings = [
{ key = "F1", mods = "None", command = "/Users/nachh/.config/scripts/toggle_mode.sh"},
{ key = "F6", mods = "None", command = "/Users/nachh/.config/scripts/darkmode.scpt"},
]
