#
# IMPORTANTE
# Para recargar la configuración basta con mandar la señal SIGUSR1,
# es decir presionar cmd + cmd + ',' 
#

hide_window_decorations titlebar-only
# window_padding_width  25 10 10
window_padding_width 5

font_family JetBrainsMono Nerd Font Mono
#font_family Hack Nerd Font Mono
font_size 13

disable_ligatures never

#Maping 42madrid symbols
symbol_map U+E800-U+E803 42madrid
# symbol_map U+F46C,U+F179,U+E286,U+F013B,U+F13B7,U+E650,U+F327,U+F0E7B,U+F15B2,U+F0497,U+F197,U+F0BC9,U+F082D,U+F287,U+F16A3,U+F16A1,U+F08C  JetBrainsMono Nerd Font
# url_color #61afef
url_style curly

map cmd+h neighboring_window left
map cmd+l neighboring_window right
map cmd+k neighboring_window up
map cmd+j neighboring_window down

map cmd+alt+p previous_tab
map cmd+alt+n next_tab
map cmd+alt+k set_tab_title
map cmd+alt+enter new_tab 


map f1 copy_to_buffer a
map f2 paste_from_buffer a
map f3 copy_to_buffer b
map f4 paste_from_buffer b

cursor_shape beam
cursor_beam_thickness 1.8

mouse_hide_wait 3.0
detect_urls yes

repaint_delay 10
input_delay 3
sync_to_monitor yes

map cmd+shift+z toggle_layout stack


tab_bar_style       custom
tab_bar_edge top
tab_separator       ""
# tab_title_template  " {title} "
tab_title_template              "  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
# tab_bar_min_tabs 1
# tab_bar_style powerline
# tab_powerline_style round
# tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}{'(%d)'%num_windows if num_windows > 1 else ''}: {(title.replace('nachh@Sentinel:', '')[:6]+'…'+title.replace('nachh@Sentinel:', '')[-6:]) if title.replace('nachh@Sentinel:', '').rindex(title.replace('nachh@Sentinel:', '')[-1]) + 1 > 13 else title.replace('nachh@Sentinel:', '')}"
#
# # inactive_tab_background #faf2d6
# inactive_tab_background #b2bfE9
# inactive_tab_foreground #000000
# tab_bar_margin_color black

map cmd+enter new_window
map cmd+shift+enter new_window_with_cwd
map cmd+shift+t new_tab_with_cwd
map f6 launch /Users/nachh/.config/scripts/darkmode.scpt
background_opacity 0.95
bell_on_tab "🔔 "
enable_audio_bell yes 

shell zsh --login


# BEGIN_KITTY_THEME
# Catppuccin-Latte
include current-theme.conf
# END_KITTY_THEME
