[colors.bright]
black = "#198388"
blue = "#277fff"
cyan = "#05a1f7"
green = "#47d4b9"
magenta = "#962ac3"
red = "#ec0101"
white = "#ffffff"
yellow = "#ff8a18"

[colors.normal]
black = "#1f2229"
blue = "#367bf0"
cyan = "#49aee6"
green = "#5ebdab"
magenta = "#9755b3"
red = "#d41919"
white = "#e6e6e6"
yellow = "#fea44c"

[colors.primary]
foreground = "#ffffff"
background = "#23252e"

[cursor]
thickness = 0.05

[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
# size = 20.0
size = 14.0

[font.bold]
# family = "CaskaydiaCove Nerd Font Propo"
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font Propo"
family = "FiraCode Nerd Font Propo"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "CaskaydiaCove Nerd Font Propo"
family = "FiraCode Nerd Font Propo"
style = "Italic"

[font.normal]
# family = "CaskaydiaCove Nerd Font Propo"
family = "FiraCode Nerd Font Propo"
style = "Regular"

[font.offset]
x = 0
y = 0

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
opacity = 0.97
dimensions = {columns = 110, lines = 28}


[window.padding]
x = 15
y = 15
