hide_window_decorations titlebar-only
# window_padding_width  25 10 10
window_padding_width  10


url_style curly

cursor_shape beam
cursor_trail 1
cursor_beam_thickness 1.8

detect_urls yes

sync_to_monitor yes

background_opacity          0.70
dynamic_background_opacity  yes
background_blur 30

# tab_bar_style custom
# tab_bar_min_tabs 1

bell_on_tab "🔔 "
enable_audio_bell yes

shell zsh --login


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16
# END_KITTY_FONTS
