#!/usr/bin/env bash

mode=$(gsettings get org.gnome.desktop.interface color-scheme)

BLUE=#3487ed
GREEN=#00802f
RED=#DB0000
WHITE=#FFFFFF
BLACK=#000000

UBUNTU_ORANGE=#E95420
LIGHT_AUBERGINE=#77216F
CANONICAL_ABUERIGNE=#772953
MID_AUBERGINE=#5E2750
DARK_AUBERGINE=#2C001E
COOL_GREY=#333333
WARM_GREY=#AEA79F

# icons
# ''
# ''
# ''
# ''
LEFT_ICON=""
RIGHT_ICON=""


SOURCE="$UBUNTU_ORANGE"
AWSPRIMARY=#232f3e
SECONDARY=#146eb4
TERCIARY=#faedca
if [[ $mode == "'prefer-dark'" ]]; then
	PRIMARY="$LIGHT_AUBERGINE"
    TAGBG=$COOL_GREY
    TAGFGDIM=$WARM_GREY
    TAGFG=$WHITE
else
	PRIMARY="$LIGHT_AUBERGINE"
    TAGFG=$WHITE
    TAGFGDIM=$COOL_GREY
    TAGBG=$WARM_GREY
fi
