set -g default-terminal "screen-256color"
set -g status-style 'bg=terminal fg={{colors.source_color.default.hex}}'
set -g status-justify left

set -g status-left-style 'bg=terminal fg={{colors.source_color.default.hex}}'
set -g status-left ' #[bg={{colors.source_color.default.hex}} fg=colour255] #S #[fg={{colors.source_color.default.hex}} bg=terminal] '
set -g status-left-length '50'
set -g status-right ' %Y-%m-%d %H:%M'
set -g status-right-style 'bg=terminal fg={{colors.source_color.default.hex}} '

# icons
# '' 
# ''
# ''
# ''

setw -g window-status-separator '' 
setw -g window-status-current-style 'fg={{colors.source_color.default.hex}} bg=terminal'
# setw -g window-status-current-style 'bg={{colors.source_color.default.hex}} fg=colour255'
setw -g window-status-current-format '#[fg=colour255 bg={{colors.source_color.default.hex}}] #F #I #W #[fg={{colors.source_color.default.hex}} bg=terminal]'

setw -g window-status-format ' #F#I #W  ' 
set -g mouse on

set -g status-position top
set -g pane-border-style 'fg=terminal'
set -g pane-active-border-style 'fg={{colors.source_color.default.hex}}'
bind r source /home/nachh/.config/tmux/tmux.conf
