bind r source ~/.config/tmux/tmux.conf

set -g prefix "M-space"

# run 'ls'
run '~/.config/tmux/themes/selector.sh'


# set -g window-status-format '#I:#W#{?window_flags,#{window_flags}, }#[range=user|kill#{window_id}](X)#[norange]'
# set -g window-status-current-format '#{E:window-status-format}'
bind -Troot MouseDown1Status if -F '#{==:#{mouse_status_range},window}' {
        select-window
} { 
	if -F '#{==:#{mouse_status_range},new}' {
        new-window
    }
} 
bind -Troot MouseDown1Status if -F '#{==:#{mouse_status_range},window}' {
        select-window
} { 
	if -F '#{m/r:^kill,#{mouse_status_range}}' {
        run -C 'kill-window -t#{s/^kill//:mouse_status_range}'
    }
	if -F '#{==:#{mouse_status_range},new}' {
        new-window
    }

}

# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# 
# # Other examples:
# # set -g @plugin 'github_username/plugin_name'
# # set -g @plugin 'github_username/plugin_name#branch'
# # set -g @plugin 'git@github.com:user/plugin'
# # set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g base-index 1
# # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.config/tmux/plugins/tpm/tpm'
