set -g default-terminal "screen-256color"
set -g status-style 'bg=terminal fg=blue'
set -g status-justify left

set -g status-left-style 'bg=terminal fg=#1960A3'
set -g status-left ' #[bg=#1960A3 fg=colour255]㉿#[fg=#1960A3 bg=gray] #S#[fg=gray bg=terminal]'
set -g status-left-length '50'
vpn_status="ifconfig tun0 2>/dev/null | grep 'inet ' | awk '{print $2}'"


%if "#{?vpn_status}"
set -g status-right ' %Y-%m-%d %H:%M #[bg=#1960A3 fg=colour255] #{vpn_status} #[fg=gray bg=terminal] '
%else
set -g status-right ' %Y-%m-%d %H:%M '
%endif
set -g status-right-style 'bg=terminal fg=blue '

# icons
# '' 
# ''
# ''
# ''

setw -g window-status-separator '' 
setw -g window-status-current-style 'fg=blue bg=terminal'
# setw -g window-status-current-style 'bg=blue fg=colour255'
# setw -g window-status-current-format '#[fg=colour255 bg=blue] #F #I #W #[fg=blue bg=terminal]'
setw -g window-status-current-format ' #[bg=blue fg=colour255]#I #[fg=terminal bg=colour12] #F#W#[fg=colour12 bg=terminal]'

# setw -g window-status-format ' #[fg=colour255 bg=blue]#I#[fg=blue bg=terminal] #F#W  ' 
setw -g window-status-format ' #[bg=blue fg=colour255]#I #[fg=blue bg=terminal] #F#W '

set -g mouse on

set -g status-position top
set -g pane-border-style 'fg=terminal'
set -g pane-active-border-style 'fg=blue'
bind r source /home/nachh/.config/tmux/tmux.conf
