set -g default-terminal "screen-256color"
set -g status-style 'bg=terminal fg=#a33d68'
set -g status-justify left

set -g status-left '#(./left_status.sh)'
set -g status-right '#(./right_status.sh)'

# icons
# '' 
# ''
# ''
# ''

setw -g window-status-separator ' '
setw -g window-status-format '#(./window_status.sh)' 
setw -g window-status-current-format '#(./window_status.sh "active")'

set -g mouse on

set -g status-position top
set -g pane-border-style 'fg=terminal'
set -g pane-active-border-style 'fg=#a33d68'
bind r source /Users/nachh/.config/tmux/tmux.conf
