set -g default-terminal "screen-256color"
set -g status-style 'fg=terminal bg=colour68'
set -g status-style 'bg=terminal fg=colour68'
set -g status-justify left

set -g status-left-style 'fg=colour68 bg=terminal'
set -g status-left-style 'bg=colour68 fg=colour255'
set -g status-left '  #S #[fg=colour68 bg=terminal]'
set -g status-left-length '20'
set -g status-right ' %Y-%m-%d %H:%M'
set -g status-right-style 'fg=terminal bg=colour68 '
set -g status-right-style 'bg=terminal fg=colour68 '

# setw -g window-status-separator '' 
setw -g window-status-separator '' 
setw -g window-status-current-style 'fg=colour68 bg=terminal'
# setw -g window-status-current-style 'bg=colour68 fg=colour255'
setw -g window-status-current-format '#[fg=colour255 bg=colour68] #F #I #W #[fg=colour68 bg=terminal]'

setw -g window-status-format '  #F #I #W #{?,,}' 
set -g mouse on

set -g status-position top
set -g pane-border-style 'fg=terminal'
set -g pane-active-border-style 'fg=colour68'
bind r source /home/nachh/.config/tmux/tmux.conf
