set -g default-terminal "screen-256color"
set -g status-style 'fg=terminal'
set -g status-justify left

set -g status-left-style 'fg=colour30 bg=terminal'
set -g status-left '  #S '
set -g status-right ' %Y-%m-%d %H:%M'

setw -g window-status-current-style 'fg=colour30 bg=terminal'
setw -g window-status-current-format '[#I #W]'

setw -g window-status-format ' #I #W ' 

set -g status-position top
set -g pane-border-style 'fg=terminal'
set -g pane-active-border-style 'fg=colour30'
bind r source /home/nachh/.config/tmux/tmux.conf
