set -g default-terminal "screen-256color"
set -g status-style 'bg=terminal fg=colour27'
set -g status-justify left

set -g status-left-style 'bg=terminal fg=colour27'
set -g status-left ' #[bg=colour27 fg=colour255]㉿ #S #[fg=colour27 bg=terminal] '
set -g status-left-length '50'
set -g status-right ' %Y-%m-%d %H:%M'
set -g status-right-style 'bg=terminal fg=colour27 '

# icons
# '' 
# ''
# ''
# ''

setw -g window-status-separator '' 
setw -g window-status-current-style 'fg=colour27 bg=terminal'
# setw -g window-status-current-style 'bg=colour27 fg=colour255'
setw -g window-status-current-format '#[fg=colour255 bg=colour27] #F #I #W #[fg=colour27 bg=terminal]'

setw -g window-status-format ' #F#I #W  ' 
set -g mouse on

set -g status-position top
set -g pane-border-style 'fg=terminal'
set -g pane-active-border-style 'fg=colour27'
bind r source /home/nachh/.config/tmux/tmux.conf
