#
[cursor]
thickness = 0.05

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
# size = 20.0
size = 12.0

[font.bold]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "Terminess Nerd Font Mono"
family = "Hack Nerd Font Propo"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "Terminess Nerd Font Mono"
family = "Hack Nerd Font Propo"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "Terminess Nerd Font Mono"
family = "Hack Nerd Font Propo"
style = "Italic"

[font.normal]
# family = "CaskaydiaCove Nerd Font Propo"
# family = "Terminess Nerd Font Mono"
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"


[window]
# decorations = "Transparent"
# decorations = "None"
# opacity = 0.85
# blur = true
# dynamic_padding = true

[window.padding]
# x = 25
# y = 25

[keyboard]
bindings = [
{ key = "F1", mods = "None", command = "/home/nachh/.config/scripts/toggle_mode.sh"},
]

[general]
import = [
    "~/.config/alacritty/themes/themes/github_light.toml"
]


[terminal]
